# Generated by Django 3.1.7 on 2021-04-07 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('cityName', models.CharField(default='', max_length=60, primary_key=True, serialize=False)),
                ('country', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('address', models.CharField(default='', max_length=60, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('cityName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='PropertyRental.location')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='', max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=60)),
                ('firstName', models.CharField(default='', max_length=60)),
                ('lastName', models.CharField(default='', max_length=60)),
                ('branchNumber', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Lister',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PropertyRental.user')),
                ('numOfListed', models.IntegerField(default=0)),
            ],
            bases=('PropertyRental.user',),
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PropertyRental.user')),
                ('numOfReservations', models.IntegerField(default=0)),
            ],
            bases=('PropertyRental.user',),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.CharField(default='', max_length=60)),
                ('endTime', models.CharField(default='', max_length=60)),
                ('length', models.IntegerField(default=0)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='PropertyRental.property')),
                ('renterID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='PropertyRental.renter')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenityType', models.CharField(default='', max_length=60)),
                ('description', models.CharField(default='', max_length=300)),
                ('propertyAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyRental.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='listerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='PropertyRental.lister'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listerBankNo', models.CharField(default='', max_length=60)),
                ('renterBankNo', models.CharField(default='', max_length=60)),
                ('amount', models.IntegerField(default=0)),
                ('reservationID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='PropertyRental.reservation')),
                ('listerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PropertyRental.lister')),
                ('renterID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PropertyRental.renter')),
            ],
        ),
    ]
