# Generated by Django 3.1.7 on 2021-04-07 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyRental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default='', max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('reservationID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='PropertyRental.reservation')),
            ],
        ),
    ]
