# Generated by Django 3.1.7 on 2021-04-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyRental', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
